# Generated by Django 6.0.2 on 2026-02-26 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('budget', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=100)),
                ('preferred_gender', models.CharField(max_length=50)),
                ('status', models.CharField(default='Open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('hourly_rate', models.CharField(max_length=50)),
                ('proposal_text', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=2)),
                ('reviews', models.IntegerField(default=0)),
                ('availability', models.CharField(default='Available Immediately', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='bookings.job')),
            ],
        ),
    ]
