# Generated by Django 6.0.2 on 2026-02-28 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_proposal_unique_together_job_awarded_teacher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='bookings.job'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('job', 'teacher')},
        ),
    ]
