# Generated by Django 6.0.2 on 2026-06-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_conversation_job_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
