# Generated by Django 6.0.2 on 2026-06-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_delete_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('proposal', 'proposal'), ('award', 'award'), ('message', 'message'), ('dispute', 'dispute')], max_length=20),
        ),
    ]
