# Generated by Django 6.0.2 on 2026-06-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_notification_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
