# Generated by Django 6.0.2 on 2026-02-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users_table',
        ),
        migrations.AlterModelTable(
            name='tutorprofile',
            table='tutor_certifications',
        ),
    ]
