# Generated by Django 6.0.2 on 2026-02-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_options_alter_customuser_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='higher_qualification',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='institute_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='teaching_experience',
            field=models.PositiveIntegerField(help_text='Experience in years', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor')], max_length=10, null=True),
        ),
    ]
