# Generated by Django 6.0.2 on 2026-06-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_studentprofile_wallettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='balance',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
