# Generated by Django 6.0.2 on 2026-06-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_is_banned_customuser_is_warned'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='cnic_image',
            field=models.ImageField(blank=True, null=True, upload_to='cnic_images/'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='unverified', max_length=20),
        ),
    ]
