# Generated by Django 6.0.2 on 2026-06-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_tutorprofile_cnic_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='subjects',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
