# Generated by Django 6.0.2 on 2026-05-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
    ]
