# Generated by Django 6.0.2 on 2026-06-13 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_delete_notification'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_state', models.CharField(choices=[('held', 'Held'), ('released', 'Released'), ('refunded', 'Refunded'), ('frozen', 'Frozen')], default='held', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_as_student', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_as_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'escrow_records',
            },
        ),
    ]
