# Generated by Django 6.0.2 on 2026-04-19 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecitationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('ayah_number', models.IntegerField()),
                ('surah_number', models.IntegerField()),
                ('audio_file', models.FileField(upload_to='recitation/')),
                ('user_text', models.TextField()),
                ('correct_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recitation_feedback_table',
                'ordering': ['created_at'],
            },
        ),
    ]
